title: Brainfuck
description: "blog"
author:
  name: "Brainfuck"
  email: ""
  url: "https://brainfucksec.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Brainfuck"
year : "2020"

# thanks tocttou for this theme
remote_theme: tocttou/hacker-blog
