title: brainfucksec
description: "Cyber Security | Privacy"
author:
  name: "brainfucksec"
  email: ""
  url: "https://brainfucksec.github.io"

baseurl: ""

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /blog/page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "brainf+ck"
year : "2022"

# thanks tocttou for this theme
remote_theme: tocttou/hacker-blog

# jekyll serve options
port: 8880 #local server port
